<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UHispatient extends Model
{
    use HasFactory;

    protected $table = 'u_hispatients';

    protected $fillable = [

        'COMPANY',
        'BRANCH',
        'CODE',
        'NE_IDSERIES',
        'NE_IDYEAR',
        'NAME',
        'DATECREATED',
        'CREATEDBY',
        'LASTUPDATED',
        'LASTUPDATEDBY',
        'RCDVERSION',
        'U_LASTNAME',
        'U_FIRSTNAME',
        'U_MIDDLENAME',
        'U_EXTNAME',
        'U_BIRTHDATE',
        'U_GENDER',
        'U_ACTIVE',
        'U_BIRTHPLACE',
        'U_ADDRESS',
        'U_CIVILSTATUS',
        'U_OCCUPATION',
        'U_NATIONALITY',
        'U_RELIGION',
        'U_FATHERNAME',
        'U_FATHERADDRESS',
        'U_FATHERTELNO',
        'U_MOTHERNAME',
        'U_MOTHERADDRESS',
        'U_MOTHERTELNO',
        'U_SPOUSENAME',
        'U_SPOUSEADDRESS',
        'U_SPOUSETELNO',
        'U_EMPLOYERNAME',
        'U_EMPLOYERADDRESS',
        'U_EMPLOYERTELNO',
        'U_CONTACTNAME',
        'U_CONTACTRELATIONSHIP',
        'U_CONTACTADDRESS',
        'U_CONTACTTELNO',
        'U_RESPONSIBLENAME',
        'U_RESPONSIBLEADDRESS',
        'U_RESPONSIBLEEMPLOYER',
        'U_RESPONSIBLETELNO',
        'U_VISITCOUNT',
        'U_TELNO',
        'U_SERIES',
        'U_CITY',
        'U_PROVINCE',
        'U_INFORMANTNAME',
        'U_INFORMANTRELATIONSHIP',
        'U_INFORMANTADDRESS',
        'U_INFORMANTTELNO',
        'U_CONFIDENTIAL',
        'U_SCDISC',
        'U_DISCCODE',
        'U_ALLERGY1',
        'U_ALLERGY2',
        'U_ALLERGY3',
        'U_ALLERGY4',
        'U_ALLERGY5',
        'U_ALLERGY6',
        'U_ALLERGY7',
        'U_COMPANY',
        'U_SSSNO',
        'U_TINNO',
        'U_CONTACTEMPLOYER',
        'U_BIRTHTIME',
        'U_REGBY',
        'U_REGDATE',
        'U_REGTIME',
        'U_EXPIREDATE',
        'U_EXPIRED',
        'U_NEWBORNSTAT',
        'NE_NEWBORN_BIRTHTIME',
        'U_RESPONSIBLERELATIONSHIP',
        'U_STREET',
        'U_BARANGAY',
        'U_ZIP',
        'U_COUNTRY',
        'U_FATHERSTREET',
        'U_FATHERBARANGAY',
        'U_FATHERCITY',
        'U_FATHERZIP',
        'U_FATHERPROVINCE',
        'U_FATHERCOUNTRY',
        'U_MOTHERSTREET',
        'U_MOTHERBARANGAY',
        'U_MOTHERCITY',
        'U_MOTHERZIP',
        'U_MOTHERPROVINCE',
        'U_MOTHERCOUNTRY',
        'U_SPOUSESTREET',
        'U_SPOUSEBARANGAY',
        'U_SPOUSECITY',
        'U_SPOUSEZIP',
        'U_SPOUSEPROVINCE',
        'U_SPOUSECOUNTRY',
        'U_EMPLOYERSTREET',
        'U_EMPLOYERBARANGAY',
        'U_EMPLOYERCITY',
        'U_EMPLOYERZIP',
        'U_EMPLOYERPROVINCE',
        'U_EMPLOYERCOUNTRY',
        'U_CONTACTSTREET',
        'U_CONTACTBARANGAY',
        'U_CONTACTCITY',
        'U_CONTACTZIP',
        'U_CONTACTPROVINCE',
        'U_CONTACTCOUNTRY',
        'U_RESPONSIBLESTREET',
        'U_RESPONSIBLEBARANGAY',
        'U_RESPONSIBLECITY',
        'U_RESPONSIBLEZIP',
        'U_RESPONSIBLEPROVINCE',
        'U_RESPONSIBLECOUNTRY',
        'U_MOBILENO',
        'U_PHICMEMBERID',
        'U_HMO',
        'U_HMOMEMBERID',
        'U_EMAIL',
        'U_FINALDIAGNOSIS',
        'updated_at',
        'created_at',
        "NE_IDTYPE",
        "NE_IDVALUE",
        'NE_SOLOPARENT',
        'U_INDIGENOUS',
        'U_PWD',
        'NE_MOTHERMRN'

    ];
}
